---
title: "Homework 5"
author: "Ikaia Leleiwi"
date: "11/11/2020"
output: pdf_document
---
#### Global Options: 
```{r  global_options}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, include = TRUE)
```

#### Packages: 
```{r libraries}
library(tidyverse)
library(lubridate)
```

#### Data:
```{r, data}
homicides <- read_csv("../data/homicide-data.csv")

homicides_clean <- homicides %>%
  filter(city == "Baltimore") %>%
  unite("victim_name", victim_first, victim_last, sep = " ") %>%
  mutate(victim_name = str_to_title(victim_name),
         reported_date = ymd(reported_date),
         month = month(reported_date, label = TRUE),
         year = year(reported_date),
         month_year = paste(month, year, sep = " "),
         season = case_when(month %in% c("May", "Jun", "Jul", 
                                         "Aug","Sep", "Oct") ~ "Summer",
                            month %in% c("Nov", "Dec", "Jan", 
                                         "Feb", "Mar", "Apr") ~ "Winter",
                            TRUE ~ "other")) %>%
  group_by(month_year, season) %>%
  count() %>%
  ungroup() %>%
  separate(month_year, into = c("month", "year"), sep = " ", remove = FALSE) %>%
  mutate(month = factor(month, levels = c("Jan", "Feb", "Mar", "Apr", "May", 
                                          "Jun", "Jul", "Aug", "Sep","Oct", 
                                          "Nov", "Dec")),
         year = factor(year),
         month_year = factor(month_year)) %>%
  group_by(year) %>%
  arrange(month, .by_group = TRUE) %>%
  ungroup() %>%
  mutate(index = seq(1:nrow(.)),
         month_year = fct_reorder(month_year, index),
         month_year = str_c(month_year, rep(1, nrow(.)), sep = " "),
         month_year = myd(month_year))
       

```

#### Plot:
```{r plot, fig.width=15, fig.height=3.5}
pal = c("gray68", "lightblue1")

 homicides_clean %>%
  ggplot(aes(x = month_year, y = n)) +
  geom_col(aes(fill = season), color = "black", size = .2) +
  geom_vline(xintercept = as.Date("2015-04-01"), 
             color = "red", linetype = 2, size = 2) +
  geom_smooth(method = "lm", formula = y ~ poly(x, 26), se = FALSE) +
  geom_text() 
  scale_fill_manual(values = pal) +
  labs(title = "Homicides in Baltimore, MD",
       x = "Date",
       y = "Monthly homicides") +
  theme(axis.text.x = element_text(size = 12),
        axis.title.x = element_text(size = 14),
        panel.background = element_rect(fill = "gray35"),
        panel.grid = element_line(color = "gray25",
                                  size = .1,
                                  linetype = 1),
        legend.position = "bottom",
        legend.title = element_blank())

```

```{r}
homicides_clean_date %>%
  ggplot() +
  geom_point(aes(x = month_year, y = n)) +
  geom_smooth(aes(x = month_year, y = n))
```

